-- Migration: Add generation_source and model_used tracking to trade_journal table
-- This allows tracking whether post-mortems were generated by LLM (primary/fallback) or deterministic fallback
-- Also adds an index for efficient querying by generation source
-- Also adds data_quality_flag to track trades with stale/incomplete data

-- Add new columns to track post-mortem generation source
ALTER TABLE trade_journal 
ADD COLUMN IF NOT EXISTS generation_source VARCHAR(32) 
CHECK (generation_source IN ('llm_primary', 'llm_fallback', 'deterministic_fallback'));

ALTER TABLE trade_journal 
ADD COLUMN IF NOT EXISTS model_used VARCHAR(64);

-- Add data_quality_flag to track trade data quality
ALTER TABLE trade_journal 
ADD COLUMN IF NOT EXISTS data_quality_flag VARCHAR(16) DEFAULT 'VALID';

-- Add index for efficient querying by generation source
CREATE INDEX IF NOT EXISTS idx_journal_generation_source ON trade_journal(generation_source, post_mortem_status);

-- Comment: This migration is additive and non-destructive, safe to run on production
